"""Add item_type to galleryitem

Revision ID: 48c762edac9d
Revises: ca165808d910
Create Date: 2025-06-22 15:14:10.834633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c762edac9d'
down_revision: Union[str, None] = 'ca165808d910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galleryitem', sa.Column('item_type', sa.Enum('IMAGE', 'VIDEO', name='itemtype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('galleryitem', 'item_type')
    # ### end Alembic commands ###
