"""Add item_type to galleryitem

Revision ID: 48c762edac9d
Revises: ca165808d910
Create Date: {您的创建日期}

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # 确保导入


# revision identifiers, used by Alembic.
revision: str = '48c762edac9d'
down_revision: Union[str, None] = 'ca165808d910' # 确保这里指向上一个版本ID
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- 1. 在文件顶部定义 ENUM 类型，方便复用 ---
item_type_enum = sa.Enum('IMAGE', 'VIDEO', name='itemtype')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- 2. 在添加列之前，先在数据库中创建 ENUM 类型 ---
    item_type_enum.create(op.get_bind(), checkfirst=False)

    # --- 3. 添加新列，并使用我们定义的 ENUM 类型 ---
    op.add_column('galleryitem', sa.Column('item_type', item_type_enum, nullable=False, server_default='IMAGE'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- 2. 先从表中移除列 ---
    op.drop_column('galleryitem', 'item_type')

    # --- 3. 再从数据库中删除 ENUM 类型 ---
    item_type_enum.drop(op.get_bind(), checkfirst=False)

    # ### end Alembic commands ###